### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:information_source: Shift detected you do not have a CI workflow using GitHub Actions. If you would like, Shift can help you get started with the [CI Generator](https://laravelshift.com/ci-generator). Although the Shift is paid, GitHub Actions is free and having a CI workflow will improve the stability and review process for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/sentinel.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "cartalyst/sentinel": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by hooman-mirghasemi** [comment]
Hi, What are you waiting for? Do you have a plane for approve this pull request for supporting laravel 11 or not?

**Comment by NByam13** [comment]
Bump Hooman's comment, would be nice to see this go in

**Comment by joshcadman01** [comment]
@hooman-mirghasemi @NByam13 - I have just forked this package with support for Laravel 11, that you can install with composer require joshcadman01/cartalyst-sentinel.

**Comment by NByam13** [comment]
@joshcadman01 much appreciated, I also forked it myself a bit ago and did the upgrade, but thank you for the ping, you're a good dude <3

**Comment by suwardany** [comment]
Apologies for the late response here, we'll look into it and if everything checks out fine, we'll release a new version by the weekend.

**Comment by LiXunGuan** [comment]
Is there no one who can merge this PR? Can any of you contact the administrator? I've sent an email but haven't received a reply.

**Comment by brunogaspar** [comment]
v8.0.0 released

**Pull request closed without merging**
