### PR TITLE
Added hack to support changes in Laravel 5.3

### PR DESCRIPTION
**Pull request by trideout**

### CODE REVIEW

**Comment by brunogaspar** [comment]
I'm not really a fan of such hacks.

We have another way to tackle this, we just need to give it a test.

**Comment by nWidart** [comment]
why not swap the arguments ? Or use `array_get` if you want to keep backwards compatibility ?

**Comment by GrahamCampbell** [comment]
You don't need a temp variable? You could do this sort of thing I guess:

https://3v4l.org/tX6Z3

**Comment by brunogaspar** [comment]
I've pushed a [feature branch](https://github.com/cartalyst/sentinel/tree/feature/laravel-53) with Laravel 5.3 support, we still need to conduct some tests on an application, but it should work now.

Closing this as the issue seems to be addressed now.

**Comment by nWidart** [comment]
Awesome! Thank you! 😄

**Pull request closed without merging**
