### PR TITLE
Allow for repositories to be configurable

### PR DESCRIPTION
**Pull request by jasonlfunk**
This pull request creates the ability for Repositories instances to be specified in addition to the Models. This was necessary for me while writing an mongo doctrine adapter for sentinel.

### CODE REVIEW

**Comment by brunogaspar** [comment]
While i understand the reason for the pull request, i must say it's not required as you can use the various setters available on the Sentinel class.

In regards of the pull request itself, i only don't like the fact that you added an entry on the config file to change the Sentinel class.
If you need to use your own class, which is perfectly fine, you can just rebind the Sentinel instance.

Will wait for @suwardany review.

**Comment by jasonlfunk** [comment]
Ah, okay. That makes sense. I didn't think to do it that way. It just seemed odd to me that the models could be swapped out via the config files but the repositories couldn't be. I can use the path you suggested, feel free to reject the pr - if you'd like

**Comment by jasonlfunk** [comment]
I'm looking at this more. My method is certainly a lot easier. Initializing the repositories isn't as easy as I hoped since the constructors have other dependencies whose interfaces aren't bound. Unless I'm missing something, I'd basically have to re-write (mostly just copy and paste) the SentinelServiceProvider. I like my solution in the PR much better - plus it fully abstracts the Eloquent/Illuminate implementation from the service provider, which seems like a plus.

I've removed the Sentinel configuration because you are right that it's fairly easy to just replace the Facade.

**Comment by suwardany** [comment]
Hello @jasonlfunk 

We appreciate your effort here, however, we'd like to keep this down to models only.

The main reason is that it is more common to swap models than the other classes, other classes can still be overridden without too much effort when needed.

**Comment by jasonlfunk** [comment]
While it's more common to swap out the models, without letting the repositories to be changed - the new models have to be Eloquent models. This provides no flexibly to use a different storage system. The repositories are already abstracted into interfaces, what's the point if the concrete implementation is not easily swappable?

If my method is wrong, can you show me what is the correct way to provide my own implementation of the repository?

**Comment by suwardany** [comment]
@jasonlfunk i did not say your method was wrong, just not something we're planning on adding to the lib.

If you're still working inside Laravel (which i assume you are), you just have to override the binding in question.

**Comment by jasonlfunk** [comment]
Yes, I am using Laravel. I can override the binding, but I'll just have to copy and paste your binding and just change 1 class name to another. It just seems like a unnecessary waste of effort.

I understand that you don't want to add it to the lib. I just don't understand why. I can't see any downside to it.

**Pull request closed without merging**
