### PR TITLE
Better tests

### PR DESCRIPTION
**Pull request by 8633brown**
these are some improved tests. all risky tests should now be fixed. I may still try to tidy them up a little more so i'm just putting a drft PR in for now. this is more for note on #473 for the tests i used to find it.

### CODE REVIEW

**Comment by 8633brown** [comment]
Also just a side note. i noticed some of the other Cartalyst repo master branches have been getting pushed to the latest version of laravel and php. i was wondering if that is in the pipeline for this project too?

**Comment by brunogaspar** [comment]
Hey @8633brown 

Yes, Sentinel will get those updates too :)

**Comment by brunogaspar** [comment]
Just checked the changes you did here, i would ask you to hold on doing more changes (so you don't waste more time on it) as i'm currently reorganising the tests and also fixing the ones that requires attention.

**Comment by 8633brown** [comment]
Youre more than welcome to close this if you think its not relevant any more.

**Comment by brunogaspar** [comment]
I've pushed all the changes i wanted to do, at least for now heh.

Feel free to continue to do your awesome work of course, i totally appreciate your effort!

**Comment by 8633brown** [comment]
Thanks. I'm relatively quite new to the programming stuff so it's at least a little confidence inspiring to view your changes and see i wasnt going too far wrong. i guess the only big difference i was going for was removing the mock connection from the Illuminate tests. and mocking the Eloquent class instead. as the connection side is being tested in the Eloquent tests anyway is this worth doing?

**Comment by brunogaspar** [comment]
> is this worth doing?

Yes, absolutely!

**Pull request closed without merging**
