### PR TITLE
Use the Dispatcher Contract

### PR DESCRIPTION
**Pull request by tomschlick**
Creating a PR for this so it doesn't get lost.

Related to #164

### CODE REVIEW

**Comment by brunogaspar** [comment]
I'm a bit against this, as it's a breaking change.

**Comment by tomschlick** [comment]
How is it breaking? The only thing that is changed is what the tests use, the app would still use the direct class that complies to the contract...

**Comment by brunogaspar** [comment]
Here https://github.com/cartalyst/sentinel/pull/178/files#diff-1511de44236dc528d9802b91870584feR28

The class that should be injected is being changed, so yeah, it's a breaking change.

**Comment by tomschlick** [comment]
But any class that implements that contract (including the previous one) would sail through no problem. 

It would only affect users who were overriding that event dispatcher & not implementing the contact... right? Or am I missing something bigger?

**Comment by brunogaspar** [comment]
> It would only affect users who were overriding that event dispatcher & not implementing the contact... right? Or am I missing something bigger?

Pretty much yes, there's probably not a lot of people doing that, but again, it goes against what semver is.

But either way, if @suwardany wants to merge it, he has my blessing :angel:

**Comment by GrahamCampbell** [comment]
You're missing a require on illuminate/contracts.

**Comment by GrahamCampbell** [comment]
While it may technically be inherited from illuminate/support, there's no reason why that should be assumed to be the case in future versions of that package.

**Pull request closed without merging**
