### PR TITLE
Added Laravel-less installation command 

### PR DESCRIPTION
**Pull request by NinoSkopac**
as per https://github.com/cartalyst/sentinel/issues/160#issuecomment-354874474

### CODE REVIEW

**Comment by camtarn** [comment]
Thanks! I was also thinking it would be a good idea to add it to the HTML manual on cartalyst.com , but adding it to the README should definitely help.

**Comment by NinoSkopac** [comment]
@camtarn agreed, but this will do just fine, people who run into issues will surely check out the github repo.

**Comment by NinoSkopac** [comment]
the tests are failing on 5.6, but this is outside the scope of this PR

**Comment by brunogaspar** [comment]
I would actually prefer to see this on the documentation rather than on the readme file.

@NinoSkopac Can you send a PR to the documentation instead? It could land under the installation step i suppose.

**Comment by dongido001** [comment]
came here for a solution and found it. would have saved me some time if it was in the documentation

**Pull request closed without merging**
