### PR TITLE
php >7.0 testing

### PR DESCRIPTION
**Pull request by 8633brown**
Ive updated travis to test the latest versions of php. there were a few issues getting the latest version of 'illuminate/database' to work correctly with the tests mainly caused by this [update](https://github.com/illuminate/database/commit/3527ce0deffb40574a7a5e39e015426905123154#diff-5baaa78be9395864ff30ebef1ae35fe9) which expects the user to have an id already set in [role tests](https://github.com/cartalyst/sentinel/compare/2.0...8633brown:7.3tests?expand=1#diff-aa67bd64c04f3283a015a992b6c8fbfcR177).

making the connections in the tests partial also solves the problem with ```BadMethodCallException: Method Mockery_13_Illuminate_Database_Connection::query() does not exist on this mock object``` errors occuring because of this update [here](https://github.com/illuminate/database/commit/d045e51923a7243f2da518fe77b4b48c1d65c58d)
i expect this to make some of the mocked methods on the connection to be useless now.

### CODE REVIEW

**Comment by brunogaspar** [comment]
Thanks for the pull request @8633brown 

Question, any reason to drop the testing on PHP 5.4 and 5.5?

I'm afraid we need to leave them there, in case we add other stuff, we surely want to test against those very old PHP versions too, since we need to still support them as the package is for PHP 5.4+.

**Comment by 8633brown** [comment]
Sorry fixed this. [phpunit](https://phpunit.de/supported-versions.html) doesnt work accross all versions we now need both versions 4 and 5.

**Comment by 8633brown** [comment]
I've removed what i believe to be redundant code if the connections are made partials [here](https://github.com/cartalyst/sentinel/compare/2.0...8633brown:7.3clean) not sure if this would be better as a separate PR or if you want me to merge it into this PR

**Comment by brunogaspar** [comment]
Looks great, thanks!

**Pull request merged**
